### ISSUE TITLE
怎么去掉power by ace啊

### ISSUE THREAD

**Issue by lxy-go** [yansenlei/VJsoneditor#10]

**Comment by yansenlei** [comment]
暂时不支持，可以自己手动处理一下

**Comment by YaEvan** [comment]
查看jsoneditor本身的api可以隐藏 
mainMenuBar: false
https://github.com/josdejong/jsoneditor/pull/596

**Comment by ArvinJIN** [comment]
用的时候设置options，直接隐藏掉上面的菜单栏，并且还要添加mode: 'code'，不然原来的设置会被覆盖掉
```
options: {
  mainMenuBar: false
  mode: 'code'
}
```
