### ISSUE TITLE
能去掉那块的字吗

### ISSUE THREAD

**Issue by Lcj-space** [yansenlei/VJsoneditor#14]
![image](https://user-images.githubusercontent.com/22415092/69021356-7a7d7780-09f2-11ea-8533-8fb0812379fd.png)

**Comment by Lcj-space** [comment]
用红色标的

**Comment by yansenlei** [comment]
参考 https://github.com/yansenlei/VJsoneditor/issues/10

**Comment by Lcj-space** [comment]
![image](https://user-images.githubusercontent.com/22415092/69110678-6733e000-0ab6-11ea-8b35-4ba8857ee952.png)
加上这个还是不行

**Comment by yansenlei** [comment]
jsoneditor的参数可以直接写在options里，参考文档 https://github.com/yansenlei/VJsoneditor#use-in-template

**Comment by Flowersea** [comment]
可以修改css
.jsoneditor-poweredBy {
  visibility: hidden;
}
