### ISSUE TITLE
dist folder missing from installed package

### ISSUE THREAD

**Issue by johnrix** [yansenlei/VJsoneditor#15]
```
npm install v-jsoneditor
```

gives a package with no `dist` folder. I should not normally have to build my dependencies before using them ... what am I missing?

**Comment by johnrix** [comment]
I see the dist folder is under /docs/ ... build issue?

**Comment by yansenlei** [comment]
`docs` is `dist`, it works fine.

**Comment by johnrix** [comment]
Well, yes, it does, as long as you adjust the path to the v-jsoneditor.min.js file accordingly. The path given in the README looks as I would have expected for a normal project setup, but it does not reflect the current reality.

'docs' is used for documentation, not the software distributables, so I don't understand why the project is set up this way.

**Comment by yansenlei** [comment]
@johnrix 
Thanks for reminding me. `docs` is really misleading. I was hoping that `docs` would be an example of a [demo](https://yansenlei.github.io/VJsoneditor/), but now I see that I need to adjust it to `dist`

**Comment by homerjam** [comment]
Yup - `docs` version also contains bundled, outdated version of `jsoneditor`. Please update the `main` property in `package.json` in the next version to use the component. Also please update `jsoneditor` dependency. Thanks!

FYI I'm using the following as a work around:

```js
import VJsoneditor from 'v-jsoneditor/src/VueJsoneditor.vue';
export default {
  components: {
    VJsoneditor,
  },
}
```
