### ISSUE TITLE
怎么使用jsoneditor 库的方法，比如树模式的expandAll, collapseAll

### ISSUE THREAD

**Issue by gongzemin** [yansenlei/VJsoneditor#17]

**Comment by yansenlei** [comment]
可以通过在上层通过refs调用到Editor实例，就可以调用jsoneditor的方法了。
```vue
<VJsoneditor v-model="json" ref="JsonEditor"></VJsoneditor>
```
```js
this.$refs.JsonEditor.editor.focus()
```

example: https://codesandbox.io/s/frosty-turing-nd7cy

**Comment by gongzemin** [comment]
有用。谢谢:)
请问是怎么知道要在this.$refs.JsonEditor后面加.editor？

**Comment by yansenlei** [comment]
组件内的jsoneditor实例：https://github.com/yansenlei/VJsoneditor/blob/master/src/VueJsoneditor.vue#L69

**Comment by gongzemin** [comment]
非常感谢 ～～

**Comment by yansenlei** [comment]
有问题可以再打开
