### ISSUE TITLE
Expecting Change Event

### ISSUE THREAD

**Issue by HDT3213** [yansenlei/VJsoneditor#22]
I hope a `change` event will be emitted when the json has changed. Thanks

**Comment by Flowersea** [comment]
I hope too.

**Comment by yansenlei** [comment]
Thanks for your issue, Now fixed, please upgrade v-jsoneditor.

```vue
<VJsoneditor v-model="json" :options="{ onChange: onChange }"></VJsoneditor>
```

**Comment by HDT3213** [comment]
Thank you very much! What a rapid response!
