### ISSUE TITLE
2 way binding not working

### ISSUE THREAD

**Issue by DeepakPant** [yansenlei/VJsoneditor#23]
I am using v-jsoneditor along with html form, I want to make 2 way editing , but editor data is not updated when model data is updated using form or Vue tab editor.

Am I doing something wrong , Value in v-jsoneditor is changed but not reflected in editor itself

**Comment by DeepakPant** [comment]
![updated](https://user-images.githubusercontent.com/596944/80302004-31162d00-87c7-11ea-8db6-abcbbe52fcfb.PNG)

![unchanged](https://user-images.githubusercontent.com/596944/80302002-2d82a600-87c7-11ea-8306-f9c3c8a2a4c3.PNG)

**Comment by yansenlei** [comment]
Fixed, Please upgrade v-jsoneditor and try again
