### ISSUE TITLE
Question about License and Attributions

### ISSUE THREAD

**Issue by lissy93** [yansenlei/VJsoneditor#43]
Hiya, really useful component - thank you for maintaining it :)

I'm using it in one of [my projects](https://github.com/lissy93/dashy), but I got a bit confused about what attribution I need to give. The original package, [`jsoneditor`](https://github.com/josdejong/jsoneditor) is licensed under `Apache-2.0`, but this project is `MIT`. Do I need to then include both licenses?

Could I also make a suggestion, that you credit [josdejong](https://github.com/josdejong) for the [original project](https://github.com/josdejong/jsoneditor) more clearly in the readme, as it looks like he's put a lot of work into this project.

Thanks, Alicia :)

**Comment by yansenlei** [comment]
Thanks for your issue. 😄 
Yep, it's a credit to the JSONEditor, and I'm happy to describe it. I will modify the files.

**Comment by lissy93** [comment]
Thank you :)
