### ISSUE TITLE
don't show double quote when content is a string or blank string 

### ISSUE THREAD

**Issue by tangyiming** [yansenlei/VJsoneditor#47]
when the content is String, the editor shows quotes. 
![image](https://user-images.githubusercontent.com/18328731/123051680-9ea60380-d434-11eb-8bde-9a51cc98c2b7.png)

how to remove these quotes？

**Comment by yansenlei** [comment]
JsonEditor itself allows string types, 
Do you expect to show an empty object? Can be external to ensure that the data is at least an empty object:
```js
<v-jsoneditor v-model="data"/>

data = data || {}

```

**Comment by tangyiming** [comment]
@yansenlei 你好，举个例子：
假如有个这个字符串: `"aaa"` ，现在Editor显示的是 `"aaa"`，但是我希望他显示的是`aaa`；
假如有个空字符串 `""`，现在Editor显示的是 `""`，但是我想看到Editor里什么也没有。
不知道要如何实现，还是实现不了呢。

**Comment by yansenlei** [comment]
实现不了，字符串必须包含引号，不用引号类型有 Boolean/Number，这是标准，应该不好改动。
强制改动样式可能与标准的显示上产生冲突。

也可以去 [jsoneditor](https://github.com/josdejong/jsoneditor) 看看能不能获得支持。

**Comment by tangyiming** [comment]
@yansenlei 好的 多谢回复
