### ISSUE TITLE
onChange throws an error, but is not included in the emit

### ISSUE THREAD

**Issue by MichaelPaulukonis** [yansenlei/VJsoneditor#6]
```
      if (error) {
        this.$emit("error")
      }
```

As a result, attempts to handle errors in the component only receive `undefined` in all cases.

I think this should be

```
      if (error) {
        this.$emit("error", error)
      }
```

**Comment by yansenlei** [comment]
@MichaelPaulukonis 

Thank you very much for your issue, already fixed in the latest version.
