### ISSUE TITLE
Operation document lacks successful callback method 'this.$emit("input", json)'

### ISSUE THREAD

**Issue by Percy6** [yansenlei/VJsoneditor#7]
Events on yarnpkg only have an Error callback; but I see a 'this.$emit("input", json)' in your source code; but this method should also appear in Events. So that users can use it better.

**Comment by yansenlei** [comment]
@Percy6 

Hi,
Are you hoping for the success callback? Watch your data changes can be met:

```vue
// comp.vue
<v-jsoneidtor v-model="data"></v-jsoneditor>
...
{
    watch: {
        data () {
            // do something...
        }
    }
}
```
