### ISSUE TITLE
光标偏移啊

### ISSUE THREAD

**Issue by lxy-go** [yansenlei/VJsoneditor#9]
再使用v-jsoneidtor时，发现格式化json后，点击变量，鼠标的光标偏移了，明明是5个0，00000现在鼠标点击到末尾，光标在第3个0 。000|00

**Comment by yansenlei** [comment]
是样式冲突了吗？如何复现？

**Comment by lxy-go** [comment]
我用element ui的时候，嵌入到里面的时候就偏移了

**Comment by yansenlei** [comment]
我尝试在elementUI中使用，看上去一切正常：https://codesandbox.io/embed/vue-template-0c92v
